### ISSUE TITLE
linux savegames disabled

### ISSUE THREAD

**Issue by spaetzlecode** [ltjax/click_to_repair#20]
please re-enable in gamestate.cpp
code was disabled because "file exists" check was not implemed in onut.
and std::filesystem::exists crashed in my quick test (WTF?)

**Comment by spaetzlecode** [comment]
from googling around, std::filesystem::exists crashes seems to be a typical Ubuntu 16.04 problem thanks to library mixes. using low level functions instead

**Comment by ltjax** [comment]
I don't think this is a good permanent solution. From what I googled, upgrading to g++9 could possibly fix this, too.

**Comment by spaetzlecode** [comment]
i don't know, using the engine's functions and implementing them with WINAPI on windows (As already in onut) and POSIX functions on linux/mac (just added) sounds reasonable, no?

**Comment by spaetzlecode** [comment]
proper solution commited
