### ISSUE TITLE
sound design

### ISSUE THREAD

**Issue by spaetzlecode** [ltjax/click_to_repair#6]
make list of sound for any action

Manage sound assets (can be delegated)

**Comment by LiMuBei** [comment]
- [x] Hover over gears sound
- [x] Hover over engine sound
- [x] Hover over hamster sound
- [x] Hover over flux capacitor sound
- [x] Machine state change sound
- [x] Level completed sound
- [x] Repair sound (wrench)
- [x] Hamster hiccup sound

**Comment by LiMuBei** [comment]
Should be done, at least stuff that was listed here.
